mode : "eureka" # "eureka", "random_signed", "random_unsigned" or "single_run_gt" or "single_run_sparse"
num_parallel_runs: 5
max_eureka_iterations: 5
env_seed: 42
gpt_model: "openai/gpt-oss-20b:free"
temperature: 1
use_cache: true